shp:

    # KAIST
    # lane: "/HD_MAP/HD_Map_KAIST_V2/2_LANE_SIDE_KAIST_V2/2_LANE_SIDE_KAIST_V2.shp"
    # link: "/HD_MAP/HD_Map_KAIST_V2/1_LANE_LINK_KAIST_V2/1_LANE_LINK_KAIST_V3.shp"
    # node: "/HD_MAP/HD_Map_KAIST_V2/6_NODES_KAIST_V2/6_NODES_KAIST_V2.shp"

    # ALPHA ( 대구 수성의료지구 )
    # lane: "/HD_MAP/HD_MAP_alpha_final/A1_LANE_V10.shp"
    # link: "/HD_MAP/HD_MAP_alpha_final/A3_LINK_V11.shp"
    # node: "/HD_MAP/HD_MAP_alpha_final/C1_NODE_V4.shp"

    # ALPHA ( 대구 수성의료지구 차선 고려)
    lane: "/HD_MAP/HD_MAP_alpha_final/final_1021/LANE.shp"
    link: "/HD_MAP/HD_MAP_alpha_final/final_1021/LINK_V2.shp"
    node: "/HD_MAP/HD_MAP_alpha_final/final_1021/NODE.shp"

    # # ALPHA ( 대구 수성의료지구 비정형)
    # lane: "/HD_MAP/HD_MAP_alpha_final/minho/MH_LANE_SHT.shp"
    # link: "/HD_MAP/HD_MAP_alpha_final/minho/MH_LINK_SHT_V2.shp"
    # node: "/HD_MAP/HD_MAP_alpha_final/minho/MH_NODE_SHT.shp"



    # # KAIST
    # lane: "/HD_MAP/HD_Map_KAIST_LINK_LANE/2_LANE_SIDE_KAIST_V2/2_LANE_SIDE_KAIST_V2.shp"
    # link: "/HD_MAP/HD_Map_KAIST_LINK_LANE/1_LANE_LINK_KAIST_V2/1_LANE_LINK_KAIST_V2.shp"
    # node: "/HD_MAP/HD_Map_KAIST_LINK_LANE/6_NODES_KAIST_V2/6_NODES_KAIST_V2.shp"
layer:
    # # KAIST
    # lane: 2_LANE_SIDE_KAIST_V2
    # link: 1_LANE_LINK_KAIST_V2
    # node: 6_NODES_KAIST_V2

    # # ALPHA ( 대구 수성의료지구)
    # lane: A1_LANE_densifiedV3
    # link: A3_LINK_reverse_densifiedV6
    # node: C1_NODEV5


    # ALPHA ( 대구 수성의료지구 차선 고려)
    lane: LANE
    link: LINK_V2
    node: NODE
    # # ALPHA ( 대구 수성의료지구 비정형)
    # lane: MH_LANE_SHT
    # link: MH_LINK_SHT_V2
    # node: MH_NODE_SHT
    # # ALPHA ( 대구 수성의료지구 )
    # lane: A1_LANE_V10
    # link: A3_LINK_V11
    # node: C1_NODE_V4

# path:
#     start: 155M00500204
#     goal: 155M02240104

# 대구
lane:
    id: 9
    right_link: 0
    left_link: 1
    lanetype: 2
    lanecode: 3
    barrier: 4
    laneno: 5
    code: 6

# # KAIST
# lane:
#     id: 0
#     right_link: 3
#     left_link: 4
#     lanetype: 1
#     lanecode: 5

# 대구
link:
    id: 0
    from_node: 1
    to_node: 2
    length: 3
    road_type: 4
    speed: 6
    left_link: 14
    right_link: 15
    next_link: 16

# # KAIST
# link:
#     id: 0
#     from_node: 1
#     to_node: 2
#     length: 3
#     speed: 6
#     left_link: 16
#     right_link: 17
#     next_link: 18

# 대구
node:
    id: 0
    next_link: 6
    prev_link: 7

# # KAIST
# node:
#     id: 0
#     next_link: 8
#     prev_link: 9

rviz_on:
    is_link_on: true
    is_node_on: true
    is_lane_on: true
    is_path_on: true
