
# QGIS에서 보고 마우스를 가져다둔 좌표에 static한 obstacle을 만들기.
# x,y 위아래로 한 쌍임.

### DAEGU ###
objects_qgis:
  x: [471221.52 , 471348.29   ]
  y: [3965780.17, 3965764.53  ]

# ### KAIST ###
# objects_qgis:
#   x: [471201.52, 0]
#   y: [3965778.74, 0]

### PG ###
objects_qgis:
  x: [445714.898, 445595.837]
  y: [3945248.001, 3945379.223]
