# yaml_mission_list 

#
#
# NOT USED IN THE MOST RECENT VERSION ! CHECK LAUNCH FILE
#
#
yaml_mission_list: [11, 12, 13]

obu_ip: 172.20.0.1
obu_port: 17001
buffer_size: 3000
sleep_rate: 100
distance_threshold: 1.0

is_v2x_on_: true
is_rehersal_: true
use_custom_mission_: false
rosbag_env: true
